[theme]
base = "dark"
primaryColor = "#001478"  # Genoverband violet
backgroundColor = "#ffffff" #"#2365fe"  # Dark background
secondaryBackgroundColor = "#0095fe"  # Dark surface
textColor = "#001478"  # Light text for dark mode
font = "sans serif"

[server]
address = "127.0.0.1"
# enableCORS = false
# port = 8501
# headless = true

# [client]
# gatherUsageStats = false
