[theme]
base = "light"
primaryColor = "#7B68EE"  # Genoverband violet
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E6E0FF"  # Light violet for secondary areas
textColor = "#2C3E50"  # Professional dark blue-gray
font = "sans serif"

[server]
address = "127.0.0.1"
# enableCORS = false
# port = 8501
# headless = true

# [client]
# gatherUsageStats = false
